repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.3
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports", "--install-types", "--non-interactive"]

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.7.3
    hooks:
      - id: pylint
        args: ["--fail-under=7.0"]
